# GeoJSON Type
scalar Coordinates

type PointGeometry {
  type: String!
  coordinates: Coordinates!
}

type RedRoseProps {
  id: Int!
  lat: Float
  lon: Float
}

type RedRosePointObject {
  type: String!
  geometry: PointGeometry
  properties: RedRoseProps
}

# Red Rose Types
type RedRoseBus {
  type: String!
  features: [RedRosePointObject]
}

type RedRoseTransit {
  single_bus(id: Int!): RedRoseBus
  all_buses: RedRoseBus
}

# Root
type Query {
  red_rose_transit: RedRoseTransit
}

type Subscription {
  red_rose_sub: RedRoseBus
}
