type Vehicle {
  id: Int!
  lat: Float
  lon: Float
}

type Query {
  single_vehicle(id: Int!): Vehicle
  all_vehicles(authority: String!): [Vehicle]
}

type Subscription {
  single_vehicle(id: Int!): Vehicle
  all_vehicles: [Vehicle]
}
